name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # JOB 1: Test the Backend
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install All Dependencies
      run: |
        npm install
        (cd BACKEND && npm install)
        (cd FRONTEND && npm install)

    - name: Run Backend Tests
      env:
        MONGO_URI: mongodb://localhost:27017/test_db
        NODE_ENV: "test"
        PORT: 3000
        
        # --- AUTH SECRETS  ---
        JWT_SECRET: "DevConnect_Test_Secret"
        JWT_REFRESH_SECRET: "DevConnect_Test_Refresh_Secret"

        # --- CLOUDINARY (Dummy values to prevent crashes) ---
        CLOUDINARY_CLOUD_NAME: "test_cloud_name"
        CLOUDINARY_API_KEY: "1234567890"
        CLOUDINARY_API_SECRET: "test_api_secret"

        # --- URL CONFIGS ---
        FRONTEND_URL: "http://localhost:5174"
        CLIENT_URL: "http://localhost:5173"
        
      run: cd BACKEND && npm run test

  # JOB 2: Build Frontend
  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-test
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install All Dependencies
      run: |
        npm install
        (cd FRONTEND && npm install)

    - name: Build Frontend
      run: cd FRONTEND && npm run build